### ISSUE TITLE
spigot.sh is_player_online function doesn't properly parse formatted server output

### ISSUE THREAD

**Issue by Bernie-McGee** [Edenhofer/abs#4]
When using the /list command with Spigot, its output is all normal text.  However, when using /list with Paper, part of the output is in bold.  This seems to make the function fail and not properly report that there are players on the server, resulting on the server closing while players are online.

I would offer a fix but have no idea how to use sed, which seems to be doing the work as far as stripping any formatting that may be present.

**Comment by Edenhofer** [comment]
Thanks for the detailed explanation. The intention of the script is to work with most minecraft servers. Hence, it should also cope with bold text in `/list`.
As soon as I have some time to spare, I will look into adapting the regex.

**Comment by Edenhofer** [comment]
Can you do me a favor and check whether the following changes cover your case and do not break spigot?
Feel free to disregard the message if you do not have the time to investigate the changes. Hopefully I can test the changes myself soon, but I do not know yet when I will have the time to do so.

Note, the changes are for the `mindecraftd.sh` script as all other scripts are mere forks of this one. The diff should also be applicable to `spigot.sh`.
```bash
diff --git a/minecraft-server/minecraftd.sh b/minecraft-server/minecraftd.sh
index 521ac2c..2218ace 100755
--- a/minecraft-server/minecraftd.sh
+++ b/minecraft-server/minecraftd.sh
@@ -86,10 +86,10 @@ is_player_online() {
        # and since playernames may not contain this string the clean player-list can easily be retrieved.
        # Otherwiese check the first digit after the last occurrence of "There are". If it is 0 then there
        # are no players on the server. Should this test fail as well. Assume that a player is online.
-       if [[ $(echo "${response}" | grep ":" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' -e 's/.*\: //' | tr -d '\n' | wc -c) -le 1 ]]; then
+       if [[ $(echo "${response}" | grep ":" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g' -e 's/.*\: //' | tr -d '\n' | wc -c) -le 1 ]]; then
                # No player is online
                return 0
-       elif [[ $(echo "${response}" | grep "There are" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' -e 's/.*\: //' -e 's/^([^.]+).*$/\1/; s/^[^0-9]*([0-9]+).*$/\1/' | tr -d '\n') -eq 0 ]]; then
+       elif [[ $(echo "${response}" | grep "There are" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g' -e 's/.*\: //' -e 's/^([^.]+).*$/\1/; s/^[^0-9]*([0-9]+).*$/\1/' | tr -d '\n') -eq 0 ]]; then
                # No player is online
                return 0
        else
```

**Comment by Bernie-McGee** [comment]
Hi, sorry for the delay.

The script seems to have the same behavior as before.  [I did capture the output of Paper's list command using Script.](https://github.com/Edenhofer/abs/files/2377253/paper.txt)  Maybe it will be helpful in seeing what kind of formatting you're up against.  I wish I could be of more help, but I'm a complete newbie when it comes to Sed.  I'm happy to do any testing, though!

**Comment by Edenhofer** [comment]
Thanks a lot for testing the diff and offering your help! The snippet made it a lot easier to pin down the problem. I am now reasonably confident that the diff below should work.

Can you do me the favor of testing it? Many thanks in advance!

```bash
diff --git a/minecraft-server/minecraftd.sh b/minecraft-server/minecraftd.sh
index 521ac2c..139bf66 100755
--- a/minecraft-server/minecraftd.sh
+++ b/minecraft-server/minecraftd.sh
@@ -86,10 +86,10 @@ is_player_online() {
        # and since playernames may not contain this string the clean player-list can easily be retrieved.
        # Otherwiese check the first digit after the last occurrence of "There are". If it is 0 then there
        # are no players on the server. Should this test fail as well. Assume that a player is online.
-       if [[ $(echo "${response}" | grep ":" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' -e 's/.*\: //' | tr -d '\n' | wc -c) -le 1 ]]; then
+       if [[ $(echo "${response}" | grep ":" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[JKmsuG]//g' -e 's/.*\: //' | tr -d '\n' | wc -c) -le 1 ]]; then
                # No player is online
                return 0
-       elif [[ $(echo "${response}" | grep "There are" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' -e 's/.*\: //' -e 's/^([^.]+).*$/\1/; s/^[^0-9]*([0-9]+).*$/\1/' | tr -d '\n') -eq 0 ]]; then
+       elif [[ $(echo "${response}" | grep "There are" | sed -r -e '$!d' -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[JKmsuG]//g' -e 's/.*\: //' -e 's/^([^.]+).*$/\1/; s/^[^0-9]*([0-9]+).*$/\1/' | tr -d '\n') -eq 0 ]]; then
                # No player is online
                return 0
        else
```

**Comment by Bernie-McGee** [comment]
Haha!  That seems to do the trick!

The script now reports correctly if someone is online.  Everything else seems to work as well, so it looks like you nailed it down.

**Comment by Edenhofer** [comment]
Great! Thanks a lot for the feedback!

I just added the changes in b1d4287ded6e6a51cfdfca55547b4646a262ff02 and pushed the necessary updates to the AUR. However, I refrained from increasing the pkgrel as I assume most users stick to using the packaged jar and are hence unaffected by the changes. Please feel free to force-rebuild the package if you want the changes to be tracked by pacman.

Thanks again for your help and for filing this bug report!
