### ISSUE TITLE
Minecraftd possible improvement - Multiple servers

### ISSUE THREAD

**Issue by Misterio77** [Edenhofer/abs#6]
Hello,
Thanks for the minecraft-server aur package (and its variants), it has really made managing minecraft servers a lot better for me.

I made a few changes to minecraftd.sh so it supports multiple servers running at once, for my own use (works great for bungeecord networks). Thought i would open an issue letting you know and sharing them back, maybe it could be useful for you or others :stuck_out_tongue_closed_eyes:.

All subcommands work with the format: `minecraftd servername subcommand`. Subservers and their individual configurations are, by default, stored in `/srv/minecraft/servers`.
All configurations, except for `game_user`, were moved from `/etc/conf.d` to the subservers config, so each server may be customized independently. I've also added a new configuration, main_root, which determines where all the subservers are at. Defaults to `/srv/${game}`.

Here's my forked script: https://github.com/Misterio77/minecraftd/blob/master/minecraftd.sh

If you want, feel free to upstream any changes. This will probbaly break a lot of workflows, so it's understandable if you don't.
I'm kinda new to packaging to aur, but i plan on uploading my fork as an alternative, when i'm done with the systemd files (still haven't looked at them), if that's okay with you.

**Comment by Edenhofer** [comment]
I surely welcome any and all contributions! If you are willing to work on the task a little more and advance the minecraft-server management script, be sure to open a pull request.

About those changes: TBH I don't like the syntax. IMHO it would be a lot cleaner if you were to add a flag with a default value s.t. if no server name is specified that some default one is chosen then.

The systemd files should work just fine. I very briefly tested them on my machine. I hope to roll them out with the next release.

**Comment by Misterio77** [comment]
I've since implemented a few more changes, specifically for working with bungeecord/waterfall networks.

The command defaults to the "proxy" when subserver is ommited (can be configured).
The "say" and "stop" command can be configured (defaulting to "alert" and "end" if the server is the proxy).
Using nmap's ncat, we can drop the connection as soon as it's received (`-i 1`), instantly starting the server (great for starting servers from inside a hub), i've also used cut to grab the requesting player's name, so it can be used for broadcasting and automatically sending that player to the starting server (they don't have to reconnect twice).
Each subserver can also be used with systemd's `@` syntax.

I've talked with bungeecord's aur maintainer, and my changes are now packaged. Also planning on packaging it for waterfall.

Here's the repo:
https://github.com/Misterio77/bungeecord-aur
And package:
https://aur.archlinux.org/packages/bungeecord/

Overall, it works great with networks, specially if you have a hub/fallback server and use [MoveMeNow](https://www.spigotmc.org/resources/movemenow.17/). The player almost never gets kicked to the menu, it's a great experience, i think.

If you have any feedback, please let me know.

**Comment by Edenhofer** [comment]
To be honest, your amendments to the management script still feel awkward. From a programming perspective it looks like a plain wrapper around the script and does not integrate nicely. IMHO it would be much cleaner if you were to introduce proper argument parsing (potentially via getopt) with optional and mandatory arguments.

Introducing default arguments for `say` and `stop` seems extremely specific. There is no clear default for what the user might want to `say`.

Furthermore, the change regarding netcat is specific to bungeecord and does not translate to other minecraft servers.

Again; if you are willing to do it properly, I would be more than happy to supervise the merge request and give you feedback. However, in its current form it is impossible to pick up changes from your script into the main server management script.

**Comment by Misterio77** [comment]
Thanks for the feedback. I will try to make it a bit more general and cleaner over the next days.

About `say` and `stop`, i don't think i understand what makes it specific? Actually, i've made it configurable so the user can specify commands other than `say` when broadcasting stop/restart messages (such as a plugin that supports colors codes).

Ncat does work on non-bungeecord servers, though. But i'll probably make it so the proxy broadcast and teleport functionalities can be disabled when using a single server. Maybe changing `PROXY_NAME` to two separate options? `DEFAULT_SERVER` and `PROXY_SERVER` maybe? (Such that if proxy_server is empty, the functionality is disabled).

Thanks again.

**Comment by Edenhofer** [comment]
Specific to your use casein the sense that they are tailored towards bungeecord.

Splitting the variables does not make this any less true. The only clear solution that I see fit is to make the management script handles multiple completely independent servers. If bungeeecord happens to be a niche were this functionality is useful than this would be awesome. However, always thinking about it in terms of portal servers and proxies is tackling the problem from the wrong direction.

**Comment by Misterio77** [comment]
I see the problem now.
What if i replaced `PROXY_NAME` with `DEFAULT_SERVER` (so the script still knows which subserver to use when omitted), and added a subserver option `IS_PROXY`, for enabling bungeecord functionality in an opt-in fashion on each subserver?
(Thus enabling the suspend broadcast and switching "say" and "stop" to "alert" and "end", without disrupting functionality for independent servers).
Maybe also a `BROADCAST` option list with servers (proxies or not) for optionally broadcasting suspend/start messages.

I fully understand if that is out of scope for the minecraftd script, though. Maybe the fork will only be useful in the bungeecord niche.

**Comment by Edenhofer** [comment]
To me, managing several generic minecraft servers (spigot, cuberite, papermc, etc.) sounds completely different to managing a bungeecord server. While multiple minecraft servers should each have their own multiplexer session as they are fully independent, a bungeecord server has a central management interface. Thus it is managed in a single multiplexer session.

If I were to build a multi-server service, I would try to isolate one server instance as much as possible from the others. Hence, I would use container software. This would not only be a lot safer but also bypass the whole problem of managing multiple servers with a single management script.
