### ISSUE TITLE
Backup full /srv/minecraft Directory

### ISSUE THREAD

**Issue by Xarius86** [Edenhofer/abs#9]
My server is now running on a Paper fork. It's easy enough to modify the the script to use the proper server jar. However, there doesn't seem to be a very good way to get `minecraftd backup` to actually back up the entire `/srv/minecraft` directory rather than individual sub-directories inside it. Any suggestions? It doesn't really like using `/srv/minecraft/*`. I know I'm probably overlooking some easy solution here.

**Comment by Edenhofer** [comment]
I think your desired behavior should work out of the box by setting `${BACKUP_PATHS}` appropriately in the config. The key fact to keep in mind is that the config is pure bash and the backup is a mere call to tar. For reference, the call looks like this:
```bash
[...] tar -C "${SERVER_ROOT}" -cf "${[...]}" ${BACKUP_PATHS} --totals ${BACKUP_FLAGS} 2>&1 | [...] "
```
Everything you specify in `${BACKUP_PATHS}` (relative to `${SERVER_ROOT}`) is backed up. Thus, if I am not mistaken, setting `BACKUP_PATHS="."` should do the trick.

**Comment by Xarius86** [comment]
Oh, man. How stupid do I look!? :D That's what trying to do things on limited sleep will do to you. I was fixated on using a wildcard in my zombie state. Thanks for the response and the obvious solution I normally would have known how to do right off the get go! :D

**Comment by Edenhofer** [comment]
No worries! You're more than welcome! :)

Btw. `BACKUP_PATHS="${SERVER_ROOT}"/*` should work too but is a little convoluted.

**Comment by Xarius86** [comment]
> Btw. `BACKUP_PATHS="${SERVER_ROOT}"/*` should work too but is a little convoluted.

I think this convoluted approach is exactly what I was attempting and failing to do. :)
